CREATE TABLE [dbo].[roominfo$] (
    [BuildingCode]        FLOAT (53)     NULL,
    [LayerCode]           FLOAT (53)     NULL,
    [SubRoomCode]         FLOAT (53)     NULL,
    [RoomName]            FLOAT (53)     NULL,
    [RoomType]            NVARCHAR (255) NULL,
    [StatusCode]          FLOAT (53)     NULL,
    [RoomPrice]           NVARCHAR (255) NULL,
    [CurrCardCount]       FLOAT (53)     NULL,
    [MaxCardCount]        FLOAT (53)     NULL,
    [IsGate]              FLOAT (53)     NULL,
    [Area1]               NVARCHAR (255) NULL,
    [Area2]               NVARCHAR (255) NULL,
    [CheckInDate]         DATETIME       NULL,
    [CheckOutDate]        DATETIME       NULL,
    [LastCheckOutDate]    NVARCHAR (255) NULL,
    [InUsed]              FLOAT (53)     NULL,
    [LockTime]            NVARCHAR (255) NULL,
    [LockType]            FLOAT (53)     NULL,
    [IsChanelMode]        FLOAT (53)     NULL,
    [PlanCheckInDate]     NVARCHAR (255) NULL,
    [PlanCheckOutDate]    NVARCHAR (255) NULL,
    [CheckInTypeCode]     FLOAT (53)     NULL,
    [PlanMakeCardCount]   FLOAT (53)     NULL,
    [GuestNames]          NVARCHAR (255) NULL,
    [Remark]              NVARCHAR (255) NULL,
    [LayerSN]             FLOAT (53)     NULL,
    [BillNo]              NVARCHAR (255) NULL,
    [PlanCheckInTypeCode] FLOAT (53)     NULL,
    [RoomCode]            FLOAT (53)     NULL,
    [LockNo]              NVARCHAR (255) NULL
);

