CREATE TABLE [BQTReservation].[BQTBooking] (
    [BookingID]                INT             IDENTITY (1, 1) NOT NULL,
    [LocationID]               INT             NOT NULL,
    [BookingModeID]            INT             NOT NULL,
    [FolioNumber]              INT             NULL,
    [ContactID]                INT             NOT NULL,
    [CompanyID]                INT             NULL,
    [EventStartDate]           DATETIME        NOT NULL,
    [EventEndDate]             DATETIME        NOT NULL,
    [EventStartTime]           DATETIME        NOT NULL,
    [EventEndTime]             DATETIME        NOT NULL,
    [BQTRooms]                 NCHAR (100)     NOT NULL,
    [MenuPlan]                 NCHAR (100)     NULL,
    [Setup]                    NCHAR (100)     NULL,
    [Notes]                    NCHAR (250)     NULL,
    [EventTypeId]              INT             NOT NULL,
    [EventNameId]              INT             NOT NULL,
    [RoomRequired]             INT             NOT NULL,
    [MediaRequired]            BIT             NOT NULL,
    [TotalPax]                 INT             NOT NULL,
    [BookingStatusId]          INT             NOT NULL,
    [TotalAmountBeforeTax]     DECIMAL (18, 4) NOT NULL,
    [TotalTaxAmount]           DECIMAL (18, 4) NOT NULL,
    [TotalAmountAfterTax]      DECIMAL (18, 4) NOT NULL,
    [TaxId]                    INT             NOT NULL,
    [TaxPercent]               INT             NOT NULL,
    [AdditionalDiscountAmount] DECIMAL (18, 4) NOT NULL,
    [TotalPayable]             DECIMAL (18, 4) NOT NULL,
    [AdvancePaid]              DECIMAL (18, 4) NOT NULL,
    [CurrencyID]               INT             NOT NULL,
    [CreatedDate]              DATETIME        NOT NULL,
    [ModifiedDate]             DATETIME        NULL,
    [CreatedBy]                INT             NOT NULL,
    [ModifiedBy]               INT             NULL,
    [RequiredAMTtoConfirm]     DECIMAL (18, 4) NOT NULL,
    [SalesManagerId]           INT             NOT NULL,
    CONSTRAINT [PK__BQTBooki__73951ACD3161E526] PRIMARY KEY CLUSTERED ([BookingID] ASC) WITH (FILLFACTOR = 90),
    FOREIGN KEY ([ContactID]) REFERENCES [contact].[Details] ([ContactID]),
    FOREIGN KEY ([ContactID]) REFERENCES [contact].[Details] ([ContactID]),
    CONSTRAINT [FK__BQTBookin__Booki__701F70F1] FOREIGN KEY ([BookingModeID]) REFERENCES [reservation].[ReservationMode] ([ReservationModeID]),
    CONSTRAINT [FK__BQTBookin__Booki__7113952A] FOREIGN KEY ([BookingStatusId]) REFERENCES [reservation].[ReservationStatus] ([ReservationStatusID])
);

