CREATE TABLE [reservation].[OTA_Reservations] (
    [OTA_Reservations_ID]     INT             IDENTITY (1, 1) NOT NULL,
    [OTA_Masters_ID]          INT             NULL,
    [Hotel_Reservation_ID]    INT             NULL,
    [Guest_Name]              VARCHAR (100)   NULL,
    [Phone_No]                VARCHAR (20)    NULL,
    [Booked_On]               VARCHAR (100)   NULL,
    [Previously_Reported]     VARCHAR (100)   NULL,
    [Guest_Email]             VARCHAR (100)   NULL,
    [Room_Type_Code]          VARCHAR (100)   NULL,
    [Room_Type_Name]          VARCHAR (100)   NULL,
    [Pricing_Model]           VARCHAR (100)   NULL,
    [Payment_Instructions]    VARCHAR (100)   NULL,
    [Cancelled_on]            VARCHAR (100)   NULL,
    [Cancelled_by]            VARCHAR (100)   NULL,
    [Check_In]                VARCHAR (100)   NULL,
    [Check-Out]               VARCHAR (100)   NULL,
    [Adults]                  INT             NULL,
    [Kids]                    INT             NULL,
    [Kids_Ages]               VARCHAR (100)   NULL,
    [Room_Nights]             INT             NULL,
    [Special_Request]         VARCHAR (100)   NULL,
    [Additional_Booking_Info] VARCHAR (200)   NULL,
    [Daily_Rate]              DECIMAL (18, 2) NULL,
    [Rate_Code]               VARCHAR (100)   NULL,
    [Extra_person]            DECIMAL (18, 2) NULL,
    [Taxes]                   DECIMAL (18, 2) NULL,
    [Extra_Charges]           DECIMAL (18, 2) NULL,
    [Total]                   DECIMAL (18, 2) NULL,
    [Is_New]                  VARCHAR (1)     NULL,
    [Is_Update]               VARCHAR (1)     NULL,
    [Is_Cancel]               VARCHAR (1)     NULL,
    [Is_Sync]                 VARCHAR (1)     NULL,
    [Currency]                VARCHAR (10)    NULL,
    [Subject]                 VARCHAR (200)   NULL,
    [Mail_Content]            NVARCHAR (MAX)  NULL,
    [Remarks]                 VARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([OTA_Reservations_ID] ASC) WITH (FILLFACTOR = 90)
);

