CREATE TABLE [reservation].[Reservation_History] (
    [ReservationID]            INT             NOT NULL,
    [FolioNumber]              INT             NOT NULL,
    [ReservationTypeID]        INT             NOT NULL,
    [ReservationModeID]        INT             NOT NULL,
    [ExpectedCheckIn]          DATETIME        NOT NULL,
    [ActualCheckIn]            DATETIME        NULL,
    [ExpectedCheckOut]         DATETIME        NOT NULL,
    [ActualCheckOut]           DATETIME        NULL,
    [GuestID]                  INT             NOT NULL,
    [Rooms]                    INT             NOT NULL,
    [Nights]                   INT             NOT NULL,
    [Adults]                   INT             NULL,
    [Children]                 INT             NULL,
    [ReservationStatusID]      INT             NOT NULL,
    [Hold_TransactionModeID]   INT             NOT NULL,
    [LocationID]               INT             NOT NULL,
    [UserID]                   INT             NOT NULL,
    [DateTime]                 DATETIME        NOT NULL,
    [CompanyID]                INT             NOT NULL,
    [TotalAmountBeforeTax]     DECIMAL (18, 4) NULL,
    [TotalTaxAmount]           DECIMAL (18, 4) NULL,
    [TotalAmountAfterTax]      DECIMAL (18, 4) NULL,
    [AdditionalDiscount]       DECIMAL (18, 4) NULL,
    [AdditionalDiscountAmount] DECIMAL (18, 4) NULL,
    [TotalPayable]             DECIMAL (18, 4) NULL,
    [RoomChargeEffectDate]     DATE            NULL,
    [OnlineReservationID]      INT             NULL,
    [CurrencyID]               INT             NOT NULL,
    [RequiredAMT]              DECIMAL (18, 2) NULL,
    [ExtraAdults]              INT             NULL,
    [CompanyTypeID]            INT             NULL,
    [ExtraChildJu]             INT             NULL,
    [ExtraChildSe]             INT             NULL,
    [AuthorizedFlag]           INT             NULL,
    [BookedRefNo]              VARCHAR (50)    NULL,
    [SalesTypeID]              INT             NULL
);

