CREATE TABLE [general].[Date] (
    [DateID]                 INT          NOT NULL,
    [Date]                   DATE         NOT NULL,
    [Day]                    TINYINT      NOT NULL,
    [DaySuffix]              CHAR (2)     NOT NULL,
    [Weekday]                TINYINT      NOT NULL,
    [WeekdayName]            VARCHAR (10) NOT NULL,
    [WeekdayNameShort]       CHAR (3)     NOT NULL,
    [WeekdayNameFirstLetter] CHAR (1)     NOT NULL,
    [DayOfYear]              SMALLINT     NOT NULL,
    [WeekOfMonth]            TINYINT      NOT NULL,
    [WeekOfYear]             TINYINT      NOT NULL,
    [Month]                  TINYINT      NOT NULL,
    [MonthName]              VARCHAR (10) NOT NULL,
    [MonthNameShort]         CHAR (3)     NOT NULL,
    [MonthNameFirstLetter]   CHAR (1)     NOT NULL,
    [Quarter]                TINYINT      NOT NULL,
    [QuarterName]            VARCHAR (6)  NOT NULL,
    [Year]                   INT          NOT NULL,
    [MMYYYY]                 CHAR (6)     NOT NULL,
    [MonthYear]              CHAR (7)     NOT NULL,
    [IsWeekend]              BIT          DEFAULT ((0)) NOT NULL,
    [IsHoliday]              BIT          DEFAULT ((0)) NOT NULL,
    [HolidayName]            VARCHAR (20) DEFAULT ('') NOT NULL,
    [SpecialDay]             VARCHAR (20) DEFAULT ('') NOT NULL,
    [FirstDateOfYear]        DATE         NULL,
    [LastDateOfYear]         DATE         NULL,
    [FirstDateOfQuater]      DATE         NULL,
    [LastDateOfQuater]       DATE         NULL,
    [FirstDateOfMonth]       DATE         NULL,
    [LastDateOfMonth]        DATE         NULL,
    [FirstDateOfWeek]        DATE         NULL,
    [LastDateOfWeek]         DATE         NULL,
    [LineageKey]             INT          NULL,
    CONSTRAINT [PK_Date] PRIMARY KEY CLUSTERED ([DateID] ASC) WITH (FILLFACTOR = 90)
);

