CREATE TABLE [fund].[Flow] (
    [FundFlowID]          INT             IDENTITY (1, 1) NOT NULL,
    [FundTypeID]          INT             NOT NULL,
    [FundFlowDirectionID] INT             NOT NULL,
    [FlowFromID]          INT             NOT NULL,
    [FlowToID]            INT             NOT NULL,
    [USDAmount]           DECIMAL (18, 6) NOT NULL,
    [SRDAmount]           DECIMAL (18, 6) NOT NULL,
    [EURAmount]           DECIMAL (18, 6) NOT NULL,
    [SealbagNumber]       VARCHAR (50)    NULL,
    [TransactionID]       INT             NULL,
    [DrawerID]            INT             NOT NULL,
    [AccountingDateID]    INT             NOT NULL,
    [DateTime]            DATETIME        NOT NULL,
    [FundFlowStatusID]    INT             NOT NULL,
    [UserShiftID]         INT             NULL,
    [UserID]              INT             NOT NULL,
    [Remarks]             VARCHAR (MAX)   NOT NULL,
    [ConfirmedBy]         INT             CONSTRAINT [DF_Flow_ConfirmedBy] DEFAULT ((0)) NULL,
    [ConfirmedOn]         DATETIME        NULL,
    [ParentFundFlowID]    INT             NULL,
    [TransferredBy]       VARCHAR (100)   NULL,
    [TransferredOn]       DATETIME        NULL,
    CONSTRAINT [PK_Flow] PRIMARY KEY CLUSTERED ([FundFlowID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Flow_FlowStatus] FOREIGN KEY ([FundFlowStatusID]) REFERENCES [fund].[FlowStatus] ([FundFlowStatusID]),
    CONSTRAINT [FK_Flow_FundFlowDirection] FOREIGN KEY ([FundFlowDirectionID]) REFERENCES [fund].[FundFlowDirection] ([FundFlowDirectionID]),
    CONSTRAINT [FK_Flow_Type] FOREIGN KEY ([FundTypeID]) REFERENCES [fund].[Type] ([FundTypeID])
);

