CREATE TYPE [cms].[dtCustomer] AS TABLE (
    [CustomerID]             BIGINT        NOT NULL,
    [FirstName]              VARCHAR (50)  NOT NULL,
    [LastName]               VARCHAR (50)  NULL,
    [ImagePath]              VARCHAR (100) NULL,
    [MiddleInitials]         VARCHAR (50)  NULL,
    [Title]                  TEXT          NULL,
    [Sex]                    VARCHAR (1)   NULL,
    [OccupationTypeID]       TINYINT       NULL,
    [OccupationType]         VARCHAR (100) NULL,
    [Address1]               VARCHAR (50)  NULL,
    [Address2]               VARCHAR (50)  NULL,
    [Telephone]              VARCHAR (50)  NULL,
    [Mobile]                 VARCHAR (50)  NULL,
    [Fax]                    VARCHAR (50)  NULL,
    [Email]                  VARCHAR (75)  NULL,
    [DateOfBirth]            DATETIME      NULL,
    [SpouseDOB]              DATE          NULL,
    [WeddingAnniversary]     DATE          NULL,
    [CustomerType]           VARCHAR (50)  NULL,
    [Reference]              VARCHAR (50)  NULL,
    [DateOfIssue]            DATETIME      NULL,
    [CustomerState]          VARCHAR (50)  NULL,
    [CountryID]              INT           NULL,
    [CountryName]            VARCHAR (100) NULL,
    [LanguageID]             TINYINT       NOT NULL,
    [Language]               VARCHAR (50)  NOT NULL,
    [IsActive]               BIT           NOT NULL,
    [CardID]                 BIGINT        NULL,
    [CategoryID]             INT           NOT NULL,
    [PRStaffID]              INT           NULL,
    [IsCardBlocked]          BIT           NOT NULL,
    [PassCode]               VARCHAR (MAX) NULL,
    [LocalIDCode]            VARCHAR (20)  NULL,
    [CasinoID]               TINYINT       NULL,
    [isImageSyncedinCentral] INT           NULL);

