CREATE TABLE [guest].[GuestCompany] (
    [CompanyID]                          INT           IDENTITY (1, 1) NOT NULL,
    [CompanyName]                        VARCHAR (100) NOT NULL,
    [CompanyAddress]                     VARCHAR (250) NOT NULL,
    [CompanyStreet]                      VARCHAR (100) NULL,
    [CompanyCity]                        VARCHAR (100) NOT NULL,
    [CompanyState]                       VARCHAR (100) NOT NULL,
    [CompanyCountryId]                   INT           NOT NULL,
    [CompanyZIP]                         VARCHAR (20)  NOT NULL,
    [CompanyPhoneNumber]                 VARCHAR (15)  NOT NULL,
    [CompanyEmail]                       VARCHAR (50)  NOT NULL,
    [POCName]                            VARCHAR (50)  NOT NULL,
    [POCDisignation]                     VARCHAR (100) NOT NULL,
    [POCPhone]                           VARCHAR (15)  NOT NULL,
    [POCEmail]                           VARCHAR (50)  NULL,
    [CreatedBy]                          INT           NOT NULL,
    [CreatedOn]                          DATETIME      NOT NULL,
    [Para1]                              VARCHAR (250) NULL,
    [Para2]                              VARCHAR (250) NULL,
    [Para3]                              DATETIME      NULL,
    [Para4]                              DATETIME      NULL,
    [Para5]                              INT           NULL,
    [Para6]                              INT           NULL,
    [ReservationTypeId]                  INT           NOT NULL,
    [IsCredit]                           BIT           NULL,
    [PaymentReceiveTypeID]               INT           NULL,
    [CreditPeriod]                       INT           NULL,
    [IsActive]                           BIT           NOT NULL,
    [IntrestPercentageAfterCreditPeriod] INT           NULL,
    CONSTRAINT [PK_GuestCompany] PRIMARY KEY CLUSTERED ([CompanyID] ASC) WITH (FILLFACTOR = 90)
);

