CREATE TABLE [account].[GuestLedgerDetails] (
    [LedgerId]                INT             IDENTITY (1, 1) NOT NULL,
    [FolioNo]                 INT             NOT NULL,
    [TransDate]               DATETIME        NOT NULL,
    [ServiceId]               INT             NOT NULL,
    [TransRefNo]              INT             NOT NULL,
    [AmtBeforeTax]            DECIMAL (18, 2) NULL,
    [TaxId]                   INT             NOT NULL,
    [TaxPer]                  DECIMAL (18, 2) NULL,
    [AmtAfterTax]             DECIMAL (18, 2) NULL,
    [PaidStatus]              INT             NOT NULL,
    [TransStatus]             INT             NOT NULL,
    [Remarks]                 VARCHAR (250)   NULL,
    [IsActive]                BIT             NULL,
    [CreatedBy]               INT             NOT NULL,
    [CreatedOn]               DATETIME        NOT NULL,
    [ModifiedBy]              INT             NULL,
    [ModifiedOn]              DATETIME        NULL,
    [AmtTax]                  DECIMAL (18, 2) NULL,
    [Credit]                  DECIMAL (18, 2) NULL,
    [Debit]                   DECIMAL (18, 2) NULL,
    [IsComplimentary]         BIT             NULL,
    [ComplimentaryPercentage] DECIMAL (18, 2) NULL,
    [UnitPriceBeforeDiscount] DECIMAL (18, 2) NULL,
    [Discount]                DECIMAL (18, 2) NULL,
    [DiscountPercentage]      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_GFDLedgerId] PRIMARY KEY CLUSTERED ([LedgerId] ASC) WITH (FILLFACTOR = 90)
);

