CREATE TABLE [account].[Transaction] (
    [TransactionID]       INT             IDENTITY (1, 1) NOT NULL,
    [TransactionTypeID]   INT             NOT NULL,
    [AccountTypeID]       INT             NOT NULL,
    [LocationID]          INT             NOT NULL,
    [ReservationID]       INT             NULL,
    [ContactID]           INT             NOT NULL,
    [Amount]              DECIMAL (18, 3) CONSTRAINT [DF_Transaction_Received] DEFAULT ((0)) NOT NULL,
    [CurrencyID]          INT             NOT NULL,
    [ActualAmount]        DECIMAL (18, 3) CONSTRAINT [DF_Transaction_ActualAmount] DEFAULT ((0)) NOT NULL,
    [ActualCurrencyID]    INT             NOT NULL,
    [ExchangeRate]        DECIMAL (18, 4) NOT NULL,
    [Remarks]             VARCHAR (MAX)   NOT NULL,
    [TransactionModeID]   INT             NOT NULL,
    [AccountingDateID]    INT             NOT NULL,
    [TransactionDateTime] DATETIME        CONSTRAINT [DF_Transaction_TransactionDateTime] DEFAULT (getdate()) NOT NULL,
    [DrawerID]            INT             CONSTRAINT [DF_Transaction_DrawerID] DEFAULT ((1)) NOT NULL,
    [UserShiftID]         INT             NULL,
    [UserID]              INT             NOT NULL,
    [CompanyID]           INT             NULL,
    [StatusId]            INT             NULL,
    [ReferenceNo]         INT             NULL,
    [GuestCompanyId]      INT             NULL,
    [GuestCompanyTypeId]  INT             NULL,
    [GuestComanyId]       INT             NULL,
    [ShortOverType]       INT             NULL,
    [FinancialDateId]     INT             NULL,
    CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED ([TransactionID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_Transaction_AccountType] FOREIGN KEY ([AccountTypeID]) REFERENCES [account].[AccountType] ([AccountTypeID]),
    CONSTRAINT [FK_Transaction_TransactionMode] FOREIGN KEY ([TransactionModeID]) REFERENCES [account].[TransactionMode] ([TransactionModeID]),
    CONSTRAINT [FK_Transaction_TransactionType] FOREIGN KEY ([TransactionTypeID]) REFERENCES [account].[TransactionType] ([TransactionTypeID])
);

