CREATE TABLE [Lock].[MakeCardRecord] (
    [AutoCode]         INT             IDENTITY (1, 1) NOT NULL,
    [CardCode]         VARCHAR (8)     NULL,
    [CardType]         NVARCHAR (20)   NULL,
    [CardTypeCode]     TINYINT         NULL,
    [LostCardCode]     VARCHAR (20)    NULL,
    [UserName]         NVARCHAR (20)   NULL,
    [UserType]         TINYINT         CONSTRAINT [DF_MakeCardRecord_UserType] DEFAULT ((1)) NULL,
    [IDType]           NVARCHAR (20)   NULL,
    [IDCode]           NVARCHAR (20)   NULL,
    [IntoRoomSumDay]   SMALLINT        NULL,
    [RoomType]         NVARCHAR (30)   NULL,
    [BuildingCode]     VARCHAR (30)    NULL,
    [Building]         NVARCHAR (30)   NULL,
    [LayerList]        VARCHAR (30)    NULL,
    [RoomCode]         VARCHAR (10)    NULL,
    [SubRoomCode]      VARCHAR (3)     NULL,
    [RoomName]         NVARCHAR (3000) NULL,
    [Operator]         NVARCHAR (20)   NULL,
    [MakeCardDate]     DATETIME        NULL,
    [ReturnCardDate]   DATETIME        NULL,
    [LostOrderDate]    DATETIME        NULL,
    [LostCardDate]     DATETIME        NULL,
    [DisableDate]      DATETIME        NULL,
    [CheckInDate]      DATETIME        NULL,
    [CheckOutDate]     DATETIME        NULL,
    [ReplaceNo]        TINYINT         NULL,
    [Tel]              VARCHAR (50)    NULL,
    [Address]          VARCHAR (50)    NULL,
    [Remark]           NVARCHAR (50)   NULL,
    [AreaList]         VARCHAR (35)    NULL,
    [ExtFloorList]     VARCHAR (20)    NULL,
    [CanOpenDBLock]    BIT             NULL,
    [ChanelMode]       BIT             NULL,
    [LockType]         TINYINT         NULL,
    [LockNoList]       VARCHAR (400)   NULL,
    [TimeSection1]     VARCHAR (15)    NULL,
    [TimeSection2]     VARCHAR (15)    NULL,
    [TimeSection3]     VARCHAR (15)    NULL,
    [IsPlanOrder]      BIT             NULL,
    [CheckInTypeCode]  TINYINT         NULL,
    [HasConsumeOrders] BIT             NULL,
    [KeyCoder]         TINYINT         NULL,
    [IDDate]           INT             NULL,
    [BillNo]           VARCHAR (20)    NULL,
    CONSTRAINT [PK__MakeCardRecord__24927208] PRIMARY KEY CLUSTERED ([AutoCode] ASC)
);

