CREATE TABLE [Lock].[RoomInfo] (
    [RoomInfoId]          INT           IDENTITY (1, 1) NOT NULL,
    [BuildingCode]        VARCHAR (3)   NOT NULL,
    [LayerCode]           VARCHAR (3)   NOT NULL,
    [RoomCode]            VARCHAR (10)  NOT NULL,
    [SubRoomCode]         VARCHAR (3)   NOT NULL,
    [RoomName]            NVARCHAR (20) NULL,
    [RoomType]            NVARCHAR (20) NULL,
    [StatusCode]          TINYINT       CONSTRAINT [DF_RoomInfo_RoomStatus] DEFAULT ((0)) NULL,
    [RoomPrice]           MONEY         NULL,
    [CurrCardCount]       INT           NULL,
    [MaxCardCount]        INT           NULL,
    [IsGate]              BIT           NULL,
    [Area1]               INT           NULL,
    [Area2]               INT           NULL,
    [CheckInDate]         DATETIME      NULL,
    [CheckOutDate]        DATETIME      NULL,
    [LastCheckOutDate]    DATETIME      NULL,
    [InUsed]              BIT           NULL,
    [LockTime]            DATETIME      NULL,
    [LockType]            TINYINT       NULL,
    [LockNo]              VARCHAR (20)  NULL,
    [IsChanelMode]        BIT           NULL,
    [PlanCheckInDate]     DATETIME      NULL,
    [PlanCheckOutDate]    DATETIME      NULL,
    [CheckInTypeCode]     TINYINT       NULL,
    [PlanMakeCardCount]   TINYINT       NULL,
    [PlanCheckInTypeCode] TINYINT       NULL,
    [GuestNames]          NVARCHAR (50) NULL,
    [Remark]              NVARCHAR (50) NULL,
    [LayerSN]             SMALLINT      NULL,
    [BillNo]              VARCHAR (20)  NULL,
    [RoomId]              INT           NULL,
    [CreatedOn]           DATETIME      NULL,
    [CreatedBy]           INT           NULL,
    [ModifiedOn]          DATETIME      NULL,
    [ModifiedBy]          INT           NULL,
    [LocationId]          INT           NULL,
    [IsActive]            BIT           NULL,
    CONSTRAINT [PK_RoomInfo] PRIMARY KEY CLUSTERED ([RoomInfoId] ASC),
    FOREIGN KEY ([RoomId]) REFERENCES [Products].[Room] ([RoomID])
);

