CREATE TABLE [service].[ConciergService] (
    [BookingID]                INT             IDENTITY (1, 1) NOT NULL,
    [BookingCode]              VARCHAR (12)    NULL,
    [ReservationID]            INT             NOT NULL,
    [ServiceItemID]            INT             NOT NULL,
    [ServiceDate]              DATE            NOT NULL,
    [ServiceFromTime]          TIME (7)        NULL,
    [ServiceToTime]            TIME (7)        NULL,
    [AdultCount]               INT             NOT NULL,
    [ChildCount]               INT             NOT NULL,
    [ServiceRate]              DECIMAL (18, 2) NULL,
    [CarSegmentID]             INT             NOT NULL,
    [CarSegmentCost]           DECIMAL (18, 2) NULL,
    [DriverID]                 INT             NOT NULL,
    [DriverRate]               DECIMAL (18, 2) NOT NULL,
    [GuideID]                  INT             NOT NULL,
    [GuideRate]                DECIMAL (18, 2) NOT NULL,
    [Discount]                 DECIMAL (18, 2) NOT NULL,
    [TotalAmountBeforeTax]     DECIMAL (18, 2) NOT NULL,
    [TaxPercent]               DECIMAL (18, 2) NOT NULL,
    [TotalTaxAmount]           DECIMAL (18, 2) NULL,
    [TotalAmountAfterTax]      DECIMAL (18, 2) NOT NULL,
    [AdditionalDiscount]       DECIMAL (18, 2) NULL,
    [AdditionalDiscountAmount] DECIMAL (18, 2) NULL,
    [RoundoffAmt]              DECIMAL (18, 2) NULL,
    [TotalPayableAmount]       DECIMAL (18, 2) NOT NULL,
    [TotalPaidAmount]          DECIMAL (18, 2) NULL,
    [RefundAmount]             DECIMAL (18, 2) NULL,
    [Hold_TransactionModeID]   INT             NULL,
    [LocationID]               INT             NOT NULL,
    [UserID]                   INT             NOT NULL,
    [DateTime]                 DATETIME        NOT NULL,
    [MainCurrencyID]           INT             NULL,
    [CurrencyID]               INT             NULL,
    [Mode]                     INT             NULL,
    [CurrencyRate]             DECIMAL (18)    NULL,
    CONSTRAINT [PK_ConciergService] PRIMARY KEY CLUSTERED ([BookingID] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_ConciergService_Item] FOREIGN KEY ([ServiceItemID]) REFERENCES [service].[Item] ([ItemID]),
    CONSTRAINT [FK_ConciergService_Reservation] FOREIGN KEY ([ReservationID]) REFERENCES [reservation].[Reservation] ([ReservationID])
);

