CREATE TABLE [Housekeeping].[HKLaundryOrderDetails] (
    [OrderDetailId] INT            IDENTITY (1, 1) NOT NULL,
    [OrderId]       INT            NULL,
    [ItemId]        INT            NULL,
    [Quantity]      INT            NULL,
    [Rate]          DECIMAL (6, 2) NULL,
    [RateClean]     DECIMAL (6, 2) NULL,
    [RatePress]     DECIMAL (6, 2) NULL,
    [RateRepair]    DECIMAL (6, 2) NULL,
    [TaxId]         INT            NULL,
    [TaxPer]        DECIMAL (6, 2) NULL,
    [ExpresCharge]  DECIMAL (6, 2) NULL,
    [ServiceCharge] DECIMAL (6, 2) NULL,
    [ReturnStatus]  INT            NULL,
    [Remarks]       VARCHAR (250)  NULL,
    [CreatedBy]     INT            NULL,
    [Createdon]     DATETIME       NULL,
    [ModifiedOn]    DATETIME       NULL,
    [ModifiedBy]    INT            NULL,
    [IsActive]      BIT            NULL,
    [Clean]         BIT            NULL,
    [Press]         BIT            NULL,
    [Repair]        BIT            NULL,
    [LineTotalBT]   DECIMAL (6, 2) NULL,
    [LineTotalTax]  DECIMAL (6, 2) NULL,
    [LineTotal]     DECIMAL (6, 2) NULL,
    [ItemRateChild] DECIMAL (6, 2) NULL,
    [Child]         BIT            NULL,
    CONSTRAINT [PK_HKLundryOrderDetails] PRIMARY KEY CLUSTERED ([OrderDetailId] ASC) WITH (FILLFACTOR = 90)
);

